services:
  frontend:
    container_name: wayshub-fe
    image: dwkelompok2/wayshub-frontend:production
    networks:
      - kelompok2
    depends_on:
      - backend

  backend:
    container_name: wayshub-be
    image: dwkelompok2/wayshub-backend:production
    env_file:
      - docker-compose.env
    environment:
      - NODE_ENV=production
    command: sh -c "./node_modules/.bin/sequelize db:migrate && node index.js"
    networks:
      - kelompok2

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - kelompok2
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend

networks:
  kelompok2:
