---
# 1. Pastikan folder konfigurasi Nginx ada di host untuk di-mount
- name: Create Nginx config directory
  file:
    path: /home/{{ new_user }}/nginx
    state: directory
    owner: "{{ new_user }}"

- name: Apply Nginx Template
  template:
    src: wayshub.j2
    dest: /home/{{ new_user }}/nginx/wayshub.conf
    mode: '0644'

# 2. Jalankan Container MySQL
- name: Run MySQL Container
  docker_container:
    name: mysql-db
    image: mysql:8.0
    state: started
    restart_policy: always
    published_ports: ["3306:3306"]
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_password }}" # Password root
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_password }}"
    volumes:
      - "/home/{{ new_user }}/mysql-data:/var/lib/mysql"
  become: yes
  become_user: "{{ new_user }}"

# 3. Jalankan Container Nginx
- name: Run Nginx Container
  docker_container:
    name: nginx-gateway
    image: nginx:alpine
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
    volumes:
      - "/home/{{ new_user }}/nginx/wayshub.conf:/etc/nginx/conf.d/default.conf:ro"
  become: yes
  become_user: "{{ new_user }}"